[general]	
name = ""
link = ""
conduct_url = ""
language = ""

[theme]
background = ""
foreground = ""
links = ""

[documents]
logo = "logo.svg"
about = "about.md"
rules = "rules.md"
verification_explanation = "verification-instructions.md"
custom_css = ""
