[general]	
name = ""
conduct_url = "" # optional + recommended: if omitted, the checkboxes in registration relating to CoC will be hidden
language = "" # Swedish, English

[documents]
logo = "logo.html"
about = "about.md"
rules = "rules.md"
verification_explanation = "verification-instructions.md"
